# Setup
name:         Project or Site name (Architect Theme)
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      "/jekyll-architect-theme"
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
