# Setup
name:         NSCoders Night - Houston
tagline:      Work on projects, get help, and discuss all things Apple.
baseurl:      "/jekyll-architect-theme"
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
